import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/base.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Bodies By Beach Bodies",
    description: "Generated by Eddie Zebo A Slight Window LLC",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}